#!/bin/bash

# BayesOptR GitHub Repository Setup Script
# This script helps you create a GitHub repository and push the package

echo "=================================================="
echo "BayesOptR GitHub Repository Setup"
echo "=================================================="
echo ""

REPO_NAME="BayesOptR"
REPO_DIR="/home/jupiter/Research/Research/BayesOptR"

cd "$REPO_DIR"

echo "Current directory: $(pwd)"
echo "Git branch: $(git branch --show-current)"
echo ""

echo "To create a GitHub repository, follow these steps:"
echo ""
echo "OPTION 1: Using GitHub Web Interface"
echo "-------------------------------------"
echo "1. Go to https://github.com/new"
echo "2. Repository name: BayesOptR"
echo "3. Description: Advanced Bayesian Optimization in R with Targeted Blocking Strategies"
echo "4. Choose: Public or Private"
echo "5. DO NOT initialize with README, .gitignore, or license (we already have these)"
echo "6. Click 'Create repository'"
echo ""
echo "7. Then run these commands:"
echo "   git remote add origin git@github.com:Masuzyo/BayesOptR.git"
echo "   git push -u origin main"
echo ""
echo "OPTION 2: Using HTTPS"
echo "---------------------"
echo "If you prefer HTTPS over SSH, use:"
echo "   git remote add origin https://github.com/Masuzyo/BayesOptR.git"
echo "   git push -u origin main"
echo ""
echo "=================================================="
echo "Package Summary"
echo "=================================================="
echo "Total files committed: $(git ls-files | wc -l)"
echo "R source files: $(find R -name '*.R' | wc -l)"
echo "Test files: $(find tests -name '*.R' 2>/dev/null | wc -l || echo 0)"
echo ""
echo "Key features:"
echo "  - Gaussian BO, Student-t BO, Adaptive Hybrid BO"
echo "  - Targeted blocking (distance-based and dimension-wise)"
echo "  - Student-t Expected Improvement"
echo "  - Parallel batch acquisition"
echo "  - Comprehensive test suite"
echo ""
echo "To verify package structure:"
echo "  R CMD check ."
echo ""
echo "To build package:"
echo "  R CMD build ."
echo ""
echo "=================================================="
